# Modify the config here and copy the file to erbs-config.toml, add it to .gitignore
# It will look for the config in these locations in this order
# 1. ./erbs-config.toml
# 2. ./config/erbs-config.toml
# 3. ../config/erbs-config.toml

title = "ERBS-BE Config"

[database]
server = "127.0.0.1"
port = 5432
name = "erbs"
username = "<put username here>"
password = "<put password here>"

[api]
key = "<put api key here>"