package models

type T struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type UserGame struct {
	UserNum          int    `json:"userNum"`
	Nickname         string `json:"nickname"`
	GameId           int    `json:"gameId"`
	SeasonId         int    `json:"seasonId"`
	MatchingMode     int    `json:"matchingMode"`
	MatchingTeamMode int    `json:"matchingTeamMode"`
	CharacterNum     int    `json:"characterNum"`
	SkinCode         int    `json:"skinCode"`
	CharacterLevel   int    `json:"characterLevel"`
	GameRank         int    `json:"gameRank"`
	PlayerKill       int    `json:"playerKill"`
	PlayerAssistant  int    `json:"playerAssistant"`
	MonsterKill      int    `json:"monsterKill"`
	BestWeapon       int    `json:"bestWeapon"`
	BestWeaponLevel  int    `json:"bestWeaponLevel"`
	MasteryLevel     []struct {
		None           int `json:"0,omitempty"`
		Glove          int `json:"1,omitempty"`
		Tonfa          int `json:"2,omitempty"`
		Bat            int `json:"3,omitempty"`
		Whip           int `json:"4,omitempty"`
		HighAngleFire  int `json:"5,omitempty"`
		DirectFire     int `json:"6,omitempty"`
		Bow            int `json:"7,omitempty"`
		Crossbow       int `json:"8,omitempty"`
		Pistol         int `json:"9,omitempty"`
		AssaultRifle   int `json:"10,omitempty"`
		SniperRifle    int `json:"11,omitempty"`
		Hammer         int `json:"13,omitempty"`
		Axe            int `json:"14,omitempty"`
		OneHandedSword int `json:"15,omitempty"`
		TwoHandedSword int `json:"16,omitempty"`
		Polearm        int `json:"17,omitempty"`
		DualSword      int `json:"18,omitempty"`
		Spear          int `json:"19,omitempty"`
		Nunchaku       int `json:"20,omitempty"`
		Rapier         int `json:"21,omitempty"`
		Guitar         int `json:"22,omitempty"`
		Camera         int `json:"23,omitempty"`
		Arcana         int `json:"24,omitempty"`
		VFArm          int `json:"25,omitempty"`
		Craft          int `json:"101"`
		Search         int `json:"102"`
		Move           int `json:"103"`
		Defense        int `json:"201"`
		Hunt           int `json:"202"`
	} `json:"masteryLevel"`
	Equipment struct {
		Weapon int `json:"0"`
		Chest  int `json:"1"`
		Head   int `json:"2"`
		Arm    int `json:"3"`
		Legs   int `json:"4"`
	} `json:"equipment"`
	VersionMajor              int            `json:"versionMajor"`
	VersionMinor              int            `json:"versionMinor"`
	Language                  string         `json:"language"`
	SkillLevelInfo            map[string]int `json:"skillLevelInfo"`
	SkillOrderInfo            map[string]int `json:"skillOrderInfo"`
	ServerName                string         `json:"serverName"`
	MaxHp                     int            `json:"maxHp"`
	MaxSp                     int            `json:"maxSp"`
	AttackPower               int            `json:"attackPower"`
	Defense                   int            `json:"defense"`
	HpRegen                   float64        `json:"hpRegen"`
	SpRegen                   float64        `json:"spRegen"`
	AttackSpeed               float64        `json:"attackSpeed"`
	MoveSpeed                 float64        `json:"moveSpeed"`
	OutOfCombatMoveSpeed      float64        `json:"outOfCombatMoveSpeed"`
	SightRange                float64        `json:"sightRange"`
	AttackRange               float64        `json:"attackRange"`
	CriticalStrikeChance      int            `json:"criticalStrikeChance"`
	CriticalStrikeDamage      int            `json:"criticalStrikeDamage"`
	CoolDownReduction         float64        `json:"coolDownReduction"`
	LifeSteal                 float64        `json:"lifeSteal"`
	NormalLifeSteal           float64        `json:"normalLifeSteal"`
	SkillLifeSteal            int            `json:"skillLifeSteal"`
	AmplifierToMonster        float64        `json:"amplifierToMonster"`
	TrapDamage                int            `json:"trapDamage"`
	BonusCoin                 int            `json:"bonusCoin"`
	GainExp                   int            `json:"gainExp"`
	BaseExp                   int            `json:"baseExp"`
	BonusExp                  int            `json:"bonusExp"`
	StartDtm                  string         `json:"startDtm"`
	Duration                  int            `json:"duration"`
	MmrBefore                 int            `json:"mmrBefore"`
	MmrGain                   int            `json:"mmrGain"`
	MmrAfter                  int            `json:"mmrAfter"`
	PlayTime                  int            `json:"playTime"`
	WatchTime                 int            `json:"watchTime"`
	TotalTime                 int            `json:"totalTime"`
	SurvivableTime            int            `json:"survivableTime"`
	BotAdded                  int            `json:"botAdded"`
	BotRemain                 int            `json:"botRemain"`
	RestrictedAreaAccelerated int            `json:"restrictedAreaAccelerated"`
	SafeAreas                 int            `json:"safeAreas"`
	TeamNumber                int            `json:"teamNumber"`
	PreMade                   int            `json:"preMade"`
	EventMissionResult        struct {
	} `json:"eventMissionResult"`
	GainedNormalMmrKFactor        int `json:"gainedNormalMmrKFactor"`
	Victory                       int `json:"victory"`
	CraftUncommon                 int `json:"craftUncommon"`
	CraftRare                     int `json:"craftRare"`
	CraftEpic                     int `json:"craftEpic"`
	CraftLegend                   int `json:"craftLegend"`
	DamageToPlayer                int `json:"damageToPlayer"`
	DamageToPlayerTrap            int `json:"damageToPlayer_trap"`
	DamageToPlayerBasic           int `json:"damageToPlayer_basic"`
	DamageToPlayerSkill           int `json:"damageToPlayer_skill"`
	DamageToPlayerItemSkill       int `json:"damageToPlayer_itemSkill"`
	DamageToPlayerDirect          int `json:"damageToPlayer_direct"`
	DamageToPlayerUniqueSkill     int `json:"damageToPlayer_uniqueSkill"`
	DamageFromPlayer              int `json:"damageFromPlayer"`
	DamageFromPlayerTrap          int `json:"damageFromPlayer_trap"`
	DamageFromPlayerBasic         int `json:"damageFromPlayer_basic"`
	DamageFromPlayerSkill         int `json:"damageFromPlayer_skill"`
	DamageFromPlayerItemSkill     int `json:"damageFromPlayer_itemSkill"`
	DamageFromPlayerDirect        int `json:"damageFromPlayer_direct"`
	DamageFromPlayerUniqueSkill   int `json:"damageFromPlayer_uniqueSkill"`
	DamageToMonster               int `json:"damageToMonster"`
	DamageToMonsterTrap           int `json:"damageToMonster_trap"`
	DamageToMonsterBasic          int `json:"damageToMonster_basic"`
	DamageToMonsterSkill          int `json:"damageToMonster_skill"`
	DamageToMonsterItemSkill      int `json:"damageToMonster_itemSkill"`
	DamageToMonsterDirect         int `json:"damageToMonster_direct"`
	DamageToMonsterUniqueSkill    int `json:"damageToMonster_uniqueSkill"`
	DamageFromMonster             int `json:"damageFromMonster"`
	DamageToPlayerShield          int `json:"damageToPlayer_Shield"`
	DamageOffsetedByShieldPlayer  int `json:"damageOffsetedByShield_Player"`
	DamageOffsetedByShieldMonster int `json:"damageOffsetedByShield_Monster"`
	KillMonsters                  struct {
		Chickens       int `json:"1,omitempty"`
		Bats           int `json:"2,omitempty"`
		Boars          int `json:"3,omitempty"`
		Dogs           int `json:"4,omitempty"`
		Wolves         int `json:"5,omitempty"`
		Bears          int `json:"6,omitempty"`
		Wickeline      int `json:"7,omitempty"`
		Alpha          int `json:"8,omitempty"`
		Omega          int `json:"9,omitempty"`
		Gamma          int `json:"10,omitempty"`
		Drone          int `json:"11,omitempty"`
		MutantChickens int `json:"12,omitempty"` //
		MutantBats     int `json:"13,omitempty"` //
		MutantBoars    int `json:"14,omitempty"` //
		MutantDogs     int `json:"15,omitempty"` // Dont know if these exist
		MutantWolves   int `json:"16,omitempty"` //
		MutantBears    int `json:"17,omitempty"` //
	} `json:"killMonsters"`
	HealAmount               int     `json:"healAmount"`
	TeamRecover              int     `json:"teamRecover"`
	ProtectAbsorb            int     `json:"protectAbsorb"`
	AddSurveillanceCamera    int     `json:"addSurveillanceCamera"`
	AddTelephotoCamera       int     `json:"addTelephotoCamera"`
	RemoveSurveillanceCamera int     `json:"removeSurveillanceCamera"`
	RemoveTelephotoCamera    int     `json:"removeTelephotoCamera"`
	UseHyperLoop             int     `json:"useHyperLoop"`
	UseSecurityConsole       int     `json:"useSecurityConsole"`
	GiveUp                   int     `json:"giveUp"`
	TeamSpectator            int     `json:"teamSpectator"`
	RouteIdOfStart           int     `json:"routeIdOfStart"`
	RouteSlotId              int     `json:"routeSlotId"`
	PlaceOfStart             string  `json:"placeOfStart"`
	MmrAvg                   int     `json:"mmrAvg"`
	MatchSize                int     `json:"matchSize"`
	TeamKill                 int     `json:"teamKill"`
	TotalFieldKill           int     `json:"totalFieldKill"`
	AccountLevel             int     `json:"accountLevel"`
	KillerUserNum            int     `json:"killerUserNum"`
	Killer                   string  `json:"killer"`
	KillDetail               string  `json:"killDetail,omitempty"`
	CauseOfDeath             string  `json:"causeOfDeath,omitempty"`
	PlaceOfDeath             string  `json:"placeOfDeath,omitempty"`
	KillerCharacter          string  `json:"killerCharacter,omitempty"`
	KillerWeapon             string  `json:"killerWeapon,omitempty"`
	KillerUserNum2           int     `json:"killerUserNum2"`
	Killer2                  string  `json:"killer2,omitempty"`
	KillDetail2              string  `json:"killDetail2,omitempty"`
	CauseOfDeath2            string  `json:"causeOfDeath2,omitempty"`
	PlaceOfDeath2            string  `json:"placeOfDeath2,omitempty"`
	KillerCharacter2         string  `json:"killerCharacter2,omitempty"`
	KillerWeapon2            string  `json:"killerWeapon2,omitempty"`
	KillerUserNum3           int     `json:"killerUserNum3"`
	Killer3                  string  `json:"killer3,omitempty"`
	KillDetail3              string  `json:"killDetail3,omitempty"`
	CauseOfDeath3            string  `json:"causeOfDeath3,omitempty"`
	PlaceOfDeath3            string  `json:"placeOfDeath3,omitempty"`
	KillerCharacter3         string  `json:"killerCharacter3,omitempty"`
	KillerWeapon3            string  `json:"killerWeapon3,omitempty"`
	FishingCount             int     `json:"fishingCount"`
	UseEmoticonCount         int     `json:"useEmoticonCount"`
	ExpireDtm                string  `json:"expireDtm"`
	TraitFirstCore           int     `json:"traitFirstCore"`
	TraitFirstSub            []int   `json:"traitFirstSub"`
	TraitSecondSub           []int   `json:"traitSecondSub"`
	AirSupplyOpenCount       []int   `json:"airSupplyOpenCount"`
	FoodCraftCount           []int   `json:"foodCraftCount"`
	BeverageCraftCount       []int   `json:"beverageCraftCount"`
	RankPoint                int     `json:"rankPoint"`
	TotalTurbineTakeOver     int     `json:"totalTurbineTakeOver"`
	UsedNormalHealPack       int     `json:"usedNormalHealPack"`
	UsedReinforcedHealPack   int     `json:"usedReinforcedHealPack"`
	UsedNormalShieldPack     int     `json:"usedNormalShieldPack"`
	UsedReinforceShieldPack  int     `json:"usedReinforceShieldPack"`
	TotalVFCredits           []int   `json:"totalVFCredits"`
	UsedVFCredits            []int   `json:"usedVFCredits"`
	SumTotalVFCredits        int     `json:"sumTotalVFCredits"`
	SumUsedVFCredits         int     `json:"sumUsedVFCredits"`
	CraftMythic              int     `json:"craftMythic"`
	PlayerDeaths             int     `json:"playerDeaths"`
	KillGamma                bool    `json:"killGamma"`
	ScoredPoint              []int   `json:"scoredPoint"`
	KillDetails              string  `json:"killDetails"`
	DeathDetails             string  `json:"deathDetails"`
	KillsPhaseOne            int     `json:"killsPhaseOne"`
	KillsPhaseTwo            int     `json:"killsPhaseTwo"`
	KillsPhaseThree          int     `json:"killsPhaseThree"`
	DeathsPhaseOne           int     `json:"deathsPhaseOne"`
	DeathsPhaseTwo           int     `json:"deathsPhaseTwo"`
	DeathsPhaseThree         int     `json:"deathsPhaseThree"`
	UsedPairLoop             int     `json:"usedPairLoop"`
	CcTimeToPlayer           float64 `json:"ccTimeToPlayer"`
	CreditSource             struct {
		PreliminaryPhase                    int     `json:"PreliminaryPhase"`
		TacticalSkillUpgrade                int     `json:"TacticalSkillUpgrade"`
		TimeElapsedCompensationByMiliSecond float64 `json:"TimeElapsedCompensationByMiliSecond"`
		TimeElapsedCreditBonusByMiliSecond  float64 `json:"TimeElapsedCreditBonusByMiliSecond"`
		KillChicken                         int     `json:"KillChicken"`
		KillBat                             int     `json:"KillBat"`
		KillBoar                            int     `json:"KillBoar"`
		KillWildDog                         int     `json:"KillWildDog"`
		KillWolf                            int     `json:"KillWolf"`
		GoldSecurityConsoleAccess           int     `json:"GoldSecurityConsoleAccess,omitempty"`
		KillMutantBoar                      int     `json:"KillMutantBoar,omitempty"`
		KillBear                            int     `json:"KillBear,omitempty"`
		KillMutantChicken                   int     `json:"KillMutantChicken,omitempty"`
		KillPlayerMerge                     int     `json:"KillPlayerMerge,omitempty"`
		KillAlpha                           int     `json:"KillAlpha,omitempty"`
		KillMutantWildDog                   int     `json:"KillMutantWildDog,omitempty"`
		KillMutantWolf                      int     `json:"KillMutantWolf,omitempty"`
		TransferConsoleSpecialMaterial      int     `json:"TransferConsoleSpecialMaterial,omitempty"`
		KillAssistDivideContribute          int     `json:"KillAssistDivideContribute,omitempty"`
		TransferConsoleRemoteDroneMySelf    int     `json:"TransferConsoleRemoteDroneMySelf,omitempty"`
		KillMutantBear                      int     `json:"KillMutantBear,omitempty"`
		ItemBounty                          int     `json:"ItemBounty,omitempty"`
		KillOmega                           int     `json:"KillOmega,omitempty"`
		TransferConsoleEscapeKey            int     `json:"TransferConsoleEscapeKey,omitempty"`
		KillMutantBat                       int     `json:"KillMutantBat,omitempty"`
		TransferConsoleResurrection         int     `json:"TransferConsoleResurrection,omitempty"`
		KillWickeline                       int     `json:"KillWickline,omitempty"`
	} `json:"creditSource"`
	BoughtInfusion         string `json:"boughtInfusion"`
	ItemTransferredConsole []int  `json:"itemTransferredConsole"`
	ItemTransferredDrone   []int  `json:"itemTransferredDrone"`
	EscapeState            int    `json:"escapeState"`
	TotalDoubleKill        int    `json:"totalDoubleKill"`
	TotalTripleKill        int    `json:"totalTripleKill"`
	TotalQuadraKill        int    `json:"totalQuadraKill"`
	TotalExtraKill         int    `json:"totalExtraKill"`
	CollectItemForLog      []int  `json:"collectItemForLog"`
	EquipFirstItemForLog   struct {
		Weapon []int `json:"0"`
		Chest  []int `json:"1"`
		Head   []int `json:"2"`
		Arm    []int `json:"3"`
		Legs   []int `json:"4"`
	} `json:"equipFirstItemForLog"`
	BattleZone1AreaCode                     int   `json:"battleZone1AreaCode"`
	BattleZone1BattleMark                   int   `json:"battleZone1BattleMark"`
	BattleZone1ItemCode                     []int `json:"battleZone1ItemCode"`
	BattleZone2AreaCode                     int   `json:"battleZone2AreaCode"`
	BattleZone2BattleMark                   int   `json:"battleZone2BattleMark"`
	BattleZone2ItemCode                     []int `json:"battleZone2ItemCode"`
	BattleZone3AreaCode                     int   `json:"battleZone3AreaCode"`
	BattleZone3BattleMark                   int   `json:"battleZone3BattleMark"`
	BattleZone3ItemCode                     []int `json:"battleZone3ItemCode"`
	BattleZonePlayerKill                    int   `json:"battleZonePlayerKill"`
	BattleZoneDeaths                        int   `json:"battleZoneDeaths"`
	BattleZone1Winner                       int   `json:"battleZone1Winner"`
	BattleZone2Winner                       int   `json:"battleZone2Winner"`
	BattleZone3Winner                       int   `json:"battleZone3Winner"`
	BattleZone1BattleMarkCount              int   `json:"battleZone1BattleMarkCount"`
	BattleZone2BattleMarkCount              int   `json:"battleZone2BattleMarkCount"`
	BattleZone3BattleMarkCount              int   `json:"battleZone3BattleMarkCount"`
	TacticalSkillGroup                      int   `json:"tacticalSkillGroup"`
	TacticalSkillLevel                      int   `json:"tacticalSkillLevel"`
	TotalGainVFCredit                       int   `json:"totalGainVFCredit"`
	KillPlayerGainVFCredit                  int   `json:"killPlayerGainVFCredit"`
	KillChickenGainVFCredit                 int   `json:"killChickenGainVFCredit"`
	KillBoarGainVFCredit                    int   `json:"killBoarGainVFCredit"`
	KillWildDogGainVFCredit                 int   `json:"killWildDogGainVFCredit"`
	KillWolfGainVFCredit                    int   `json:"killWolfGainVFCredit"`
	KillBearGainVFCredit                    int   `json:"killBearGainVFCredit"`
	KillOmegaGainVFCredit                   int   `json:"killOmegaGainVFCredit"`
	KillBatGainVFCredit                     int   `json:"killBatGainVFCredit"`
	KillWicklineGainVFCredit                int   `json:"killWicklineGainVFCredit"`
	KillAlphaGainVFCredit                   int   `json:"killAlphaGainVFCredit"`
	KillItemBountyGainVFCredit              int   `json:"killItemBountyGainVFCredit"`
	KillDroneGainVFCredit                   int   `json:"killDroneGainVFCredit"`
	KillGammaGainVFCredit                   int   `json:"killGammaGainVFCredit"`
	KillTurretGainVFCredit                  int   `json:"killTurretGainVFCredit"`
	ItemShredderGainVFCredit                int   `json:"itemShredderGainVFCredit"`
	TotalUseVFCredit                        int   `json:"totalUseVFCredit"`
	RemoteDroneUseVFCreditMySelf            int   `json:"remoteDroneUseVFCreditMySelf"`
	RemoteDroneUseVFCreditAlly              int   `json:"remoteDroneUseVFCreditAlly"`
	TransferConsoleFromMaterialUseVFCredit  int   `json:"transferConsoleFromMaterialUseVFCredit"`
	TransferConsoleFromEscapeKeyUseVFCredit int   `json:"transferConsoleFromEscapeKeyUseVFCredit"`
	TransferConsoleFromRevivalUseVFCredit   int   `json:"transferConsoleFromRevivalUseVFCredit"`
	TacticalSkillUpgradeUseVFCredit         int   `json:"tacticalSkillUpgradeUseVFCredit"`
	InfusionReRollUseVFCredit               int   `json:"infusionReRollUseVFCredit"`
	InfusionTraitUseVFCredit                int   `json:"infusionTraitUseVFCredit"`
	InfusionRelicUseVFCredit                int   `json:"infusionRelicUseVFCredit"`
	InfusionStoreUseVFCredit                int   `json:"infusionStoreUseVFCredit"`
	TeamElimination                         int   `json:"teamElimination"`
	TeamDown                                int   `json:"teamDown"`
	TeamBattleZoneDown                      int   `json:"teamBattleZoneDown"`
	TeamRepeatDown                          int   `json:"teamRepeatDown"`
	AdaptiveForce                           int   `json:"adaptiveForce"`
	AdaptiveForceAttack                     int   `json:"adaptiveForceAttack"`
	AdaptiveForceAmplify                    int   `json:"adaptiveForceAmplify"`
	SkillAmp                                int   `json:"skillAmp"`
	CampFireCraftUncommon                   int   `json:"campFireCraftUncommon"`
	CampFireCraftRare                       int   `json:"campFireCraftRare"`
	CampFireCraftEpic                       int   `json:"campFireCraftEpic"`
	CampFireCraftLegendary                  int   `json:"campFireCraftLegendary"`
	CobaltRandomPickRemoveCharacter         int   `json:"cobaltRandomPickRemoveCharacter"`
	TacticalSkillUseCount                   int   `json:"tacticalSkillUseCount"`
	CreditRevivalCount                      int   `json:"creditRevivalCount"`
	CreditRevivedOthersCount                int   `json:"creditRevivedOthersCount"`
	TimeSpentInBriefingRoom                 int   `json:"timeSpentInBriefingRoom"`
	IsLeavingBeforeCreditRevivalTerminate   bool  `json:"IsLeavingBeforeCreditRevivalTerminate"`
	CrGetAnimal                             int   `json:"crGetAnimal"`
	CrGetMutant                             int   `json:"crGetMutant"`
	CrGetPhaseStart                         int   `json:"crGetPhaseStart"`
	CrGetKill                               int   `json:"crGetKill"`
	CrGetAssist                             int   `json:"crGetAssist"`
	CrGetTimeElapsed                        int   `json:"crGetTimeElapsed"`
	CrGetCreditBonus                        int   `json:"crGetCreditBonus"`
	CrUseRemoteDrone                        int   `json:"crUseRemoteDrone"`
	CrUseUpgradeTacticalSkill               int   `json:"crUseUpgradeTacticalSkill"`
	CrUseTreeOfLife                         int   `json:"crUseTreeOfLife"`
	CrUseMeteorite                          int   `json:"crUseMeteorite"`
	CrUseMythril                            int   `json:"crUseMythril"`
	CrUseForceCore                          int   `json:"crUseForceCore"`
	CrUseVFBloodSample                      int   `json:"crUseVFBloodSample"`
	CrUseActivationModule                   int   `json:"crUseActivationModule"`
	CrUseRootkit                            int   `json:"crUseRootkit"`
	MmrGainInGame                           int   `json:"mmrGainInGame"`
	MmrLossEntryCost                        int   `json:"mmrLossEntryCost"`
	PremadeMatchingType                     int   `json:"premadeMatchingType"`
	ViewContribution                        int   `json:"viewContribution"`
	UseReconDrone                           int   `json:"useReconDrone"`
	UseEmpDrone                             int   `json:"useEmpDrone"`
	ExceptPreMadeTeam                       bool  `json:"exceptPreMadeTeam"`
	IsLeavingBeforeCreditRevivalTerminate1  bool  `json:"isLeavingBeforeCreditRevivalTerminate"`
}

type TopRank struct {
	UserNum     int    `json:"userNum"`
	Nickname    string `json:"nickname"`
	Rank        int    `json:"rank"`
	Mmr         int    `json:"mmr"`
	UserEmblems []int  `json:"userEmblems"` // mysterious field
}

type UserRank struct {
	UserNum  int    `json:"userNum"`
	Mmr      int    `json:"mmr"`
	Nickname string `json:"nickname"`
	Rank     int    `json:"rank"`
}

type UserInfo struct {
	UserNum  int    `json:"userNum"`
	Nickname string `json:"nickname"`
}

type UserStats struct {
	SeasonId          int     `json:"seasonId"`
	UserNum           int     `json:"userNum"`
	MatchingMode      int     `json:"matchingMode"`
	MatchingTeamMode  int     `json:"matchingTeamMode"`
	Mmr               int     `json:"mmr"`
	Nickname          string  `json:"nickname"`
	Rank              int     `json:"rank"`
	RankSize          int     `json:"rankSize"`
	TotalGames        int     `json:"totalGames"`
	TotalWins         int     `json:"totalWins"`
	TotalTeamKills    int     `json:"totalTeamKills"`
	TotalDeaths       int     `json:"totalDeaths"`
	EscapeCount       int     `json:"escapeCount"`
	RankPercent       float64 `json:"rankPercent"`
	AverageRank       float64 `json:"averageRank"`
	AverageKills      float64 `json:"averageKills"`
	AverageAssistants float64 `json:"averageAssistants"`
	AverageHunts      float64 `json:"averageHunts"`
	Top1              float64 `json:"top1"`
	Top2              float64 `json:"top2"`
	Top3              float64 `json:"top3"`
	Top5              float64 `json:"top5"`
	Top7              float64 `json:"top7"`
	CharacterStats    []struct {
		CharacterCode int `json:"characterCode"`
		TotalGames    int `json:"totalGames"`
		Usages        int `json:"usages"`
		MaxKillings   int `json:"maxKillings"`
		Top3          int `json:"top3"`
		Wins          int `json:"wins"`
		Top3Rate      int `json:"top3Rate"`
		AverageRank   int `json:"averageRank"`
	} `json:"characterStats"`
}

type Result struct {
	RecommendWeaponRoute struct {
		Id                     int     `json:"id"`
		Title                  string  `json:"title"`
		UserNum                int     `json:"userNum"`
		UserNickname           string  `json:"userNickname"`
		CharacterCode          int     `json:"characterCode"`
		SlotId                 int     `json:"slotId"`
		WeaponType             int     `json:"weaponType"`
		WeaponCodes            string  `json:"weaponCodes"`
		TacticalSkillGroupCode int     `json:"tacticalSkillGroupCode"`
		Paths                  string  `json:"paths"`
		Count                  int     `json:"count"`
		Version                string  `json:"version"`
		TeamMode               int     `json:"teamMode"`
		LanguageCode           string  `json:"languageCode"`
		RouteVersion           int     `json:"routeVersion"`
		Share                  bool    `json:"share"`
		UpdateDtm              int64   `json:"updateDtm"`
		V2Like                 int     `json:"v2Like"`
		V2WinRate              float64 `json:"v2WinRate"`
		V2SeasonId             int     `json:"v2SeasonId"`
		V2AccumulateLike       int     `json:"v2AccumulateLike"`
		V2AccumulateWinRate    float64 `json:"v2AccumulateWinRate"`
		V2AccumulateSeasonId   int     `json:"v2AccumulateSeasonId"`
	} `json:"recommendWeaponRoute"`
	RecommendWeaponRouteDesc struct {
		RecommendWeaponRouteId int    `json:"recommendWeaponRouteId"`
		SkillPath              string `json:"skillPath,omitempty"`
		Desc                   string `json:"desc,omitempty"`
	} `json:"recommendWeaponRouteDesc"`
}
